version: '3'

services:
  api:
    build: .
    image: discount-api
    container_name: discount-api
    links:
      - mongo
    depends_on:
      - mongo
    env_file:
      - .development.env
    volumes:
       - .:/usr/app
       - /usr/app/node_modules
    working_dir: /usr/app
    ports:
       - "${PORT}:${PORT}"
    command: npm run start:dev

  mongo:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    volumes:
      - mongo_data:/data/db
    env_file:
      .development.env
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_USER_PASSWORD}
    command: mongod --quiet --logpath /dev/null

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis:/usr/redis

volumes:
  redis:
    driver: local
  mongo_data: